import React from "react";
import "./iaL.css";

function IA() {
  return (
    <>
      <div className="custom-sectiono">
        <div className="texto-side">
          <h2>Expertise en IA pour l'Industrie Financière</h2>
          <div className="l">
            <div className="underline-wrapper">
              <div className="elementskit-border-divider"></div>
              <div className="title-line"></div>
            </div>
          </div>
          <p>
            Explorez comment notre société éditrice de logiciels intègre avec
            maîtrise les dernières avancées en intelligence artificielle pour
            révolutionner l'industrie financière. Plongez dans notre expertise
            en IA et découvrez comment nous utilisons des algorithmes de pointe
            pour développer des solutions logicielles personnalisées répondant
            aux défis uniques des institutions financières d'aujourd'hui.
          </p>
        </div>

        <div className="image-sideo">
          <img
            src="https://i.pinimg.com/736x/53/cb/dc/53cbdc2b048e91bd0c0c49ea4599ee69.jpg"
            className="main-img ls"
          />
          <img
            src="https://fininfosolutions.com/wp-content/uploads/2024/03/b55a298f-itfp-shape-3-1.png"
            className="bg-deco m"
          />
        </div>
      </div>

      {/* // section 2 */}

      <div class="customo-sectiono">
        <div class="image-sideo">
          <img
            src="https://fininfosolutions.com/wp-content/uploads/2024/03/ai-changing-the-future-of-mobile-banking-apps-1.jpg"
            class="main-imgo fd"
          />
          <img
            src="https://fininfosolutions.com/wp-content/uploads/2024/03/514755c1-service-shape-2-1.png"
            class="bg-decot"
          />
        </div>

        <div class="texto-sideo">
          <h2 className="pst">
            {"Solutions Innovantes pour un Avenir Financier Intelligent"}
          </h2>
          <div className="l">
            <div className="underline-wrapper">
              <div className="elementskit-border-divider"></div>
              <div className="title-line"></div>
            </div>
          </div>
          <p>
            Découvrez nos produits logiciels de pointe conçus spécifiquement
            pour aider les institutions financières à prospérer dans un paysage
            en constante évolution. Explorez nos outils d'IA sophistiqués qui
            optimisent la gestion des risques, améliorent l'efficacité
            opérationnelle et offrent des insights précieux pour une prise de
            décision stratégique.
          </p>
        </div>
      </div>
      {/* section 3 */}
      <div className="customp-sectiono me">
        <div className="textok-side">
          <h2>Collaboration Stratégique pour le Succès</h2>
          <div className="lp">
            <div className="underline-wrapper">
              <div className="elementskit-border-divider"></div>
              <div className="title-line"></div>
            </div>
          </div>
          <p>
            Notre engagement envers nos clients va au-delà de la simple
            fourniture de logiciels. Nous sommes des partenaires stratégiques
            dans votre parcours vers l'excellence financière. Découvrez comment
            notre équipe dévouée travaille en étroite collaboration avec vous
            pour comprendre vos besoins uniques, développer des solutions sur
            mesure et vous accompagner à chaque étape de votre transformation
            numérique.
          </p>
        </div>

        <div className="imagei-sideo">
          <img
            src="https://fininfosolutions.com/wp-content/uploads/2024/03/shutterstock-2264674961_3_1732.webp"
            className="mainp-img kt"
          />
          <img
            src="https://fininfosolutions.com/wp-content/uploads/2024/03/514755c1-service-shape-2-1.png"
            className="bgo-deco ptr"
          />
        </div>
      </div>
      
    </>
  );
}

export default IA;
